apiVersion: v1
kind: Service
metadata:
  name: application-golang-service
  namespace: core
spec:
  selector:
    app: application-golang
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http